rts/Sim/Weapons/Weapon.cpp, rts/Sim/Weapons/Weapon.h, rts/Sim/Weapons/WeaponDef.cpp, rts/Sim/Weapons/WeaponDef.h, rts/Sim/Weapons/WeaponLoader.cpp
For ticket http://springrts.com/mantis/view.php?id=4641
Default is 90 degrees.
Burst weapons ignore this after the burst begins. Luckily that is a rare case.
=> Added firetolerance tag

rts/System/Platform/Linux/CrashHandler.cpp
Will replace not found debug symbols
[f=0000000] [CrashHandler] Warning: [03]        ??:?  _nv019glcore
with raw output of backtrace_symbol:
[f=0000000] [CrashHandler] Warning: [03] /usr/lib/libnvidia-glcore.so.343.36(+0x1339308) [0x7f007c460308]  _nv019glcore
More info - better, imho.
=> More info in linux LogStacktrace()

rts/Sim/Weapons/WeaponDef.cpp
Due to having externalName("accuracy")
=> movingAccuracy was entirely disregarded

rts/Rendering/Env/AdvWater.cpp, rts/Rendering/Env/DynWater.cpp, rts/Rendering/Shaders/LuaShaderContainer.cpp, rts/Rendering/Shaders/Shader.cpp, rts/Rendering/Shaders/ShaderStates.h
Clears flags cashe in GLSLProgramObject::Release() so that when you call LoadFromLua() shaders are recompiled properly.
This fixes InfoTextures not working with the error:
```
[f=0000000] [Shader] Warning: [GLSL-PO::Link] program-object name: CInfoTextureCombiner, link-log:
Link info
---------
No shader objects attached.
[f=0000000] Error: CInfoTextureCombiner-shader compilation error: Link info
---------
No shader objects attached.
```
=> Fix InfoTexture bugs

rts/ExternalAI/Interface/SSkirmishAICallback.h, rts/ExternalAI/SSkirmishAICallbackImpl.cpp, rts/ExternalAI/SSkirmishAICallbackImpl.h, rts/Map/MapInfo.cpp, rts/Map/MapInfo.h
Currently there is no nice way to identify if water is appropriate place for buildings, except for parsing map's .smd
http://springrts.com/mantis/view.php?id=4676
SIDENOTE: Does next code know that water.damage is already scaled by ((float)UNIT_SLOWUPDATE_RATE / GAME_SPEED)?
@see https://github.com/spring/spring/blob/36f68e956d0e6ca45b03d9dc27d717084c43503e/rts/Sim/MoveTypes/MoveDefHandler.cpp#L130-L132
I think water.damage for that part of code should be scaled back with (GAME_SPEED/UNIT_SLOWUPDATE_RATE).
=> [AI] Add Map::GetWaterDamage

rts/Game/GameHelper.cpp
The distance to collision volume check is bypassed for impactOnly weapons. These weapons must have impacted the collision volume to deal their damage so they are known to be at distance 0.
=> Optimization for explosion damage

rts/Sim/Weapons/PlasmaRepulser.cpp
This was done by treating explosions caused by shields as if the projectile exploded mid-air. Previously they were treated as if they collided with the owner of the shield. This change should improve the consistency.
=> Fixed impactOnly weapons dealing damage to the owner of the shield. 

rts/Sim/Weapons/BeamLaser.cpp, rts/Sim/Weapons/LightningCannon.cpp
This fixes the bug in which an impactOnly BeamLaser or LightningCannon deals damage even when it is blocked by water or a shield.
=> Fix impactOnly laser shield bug.

rts/Sim/Units/Unit.cpp
haveUserTarget is already set in
https://github.com/spring/spring/blob/868b2a0bdcbae486553838509ee97ad4dc5808ac/rts/Sim/Weapons/Weapon.cpp#L622
or
https://github.com/spring/spring/blob/868b2a0bdcbae486553838509ee97ad4dc5808ac/rts/Sim/Weapons/Weapon.cpp#L654
When set also in the change location, all weapons automatically get haveUserTarget status even if they target a different target (since they can't target the user one).
=> Fix User target being set for all weapons

rts/Game/GameHelper.cpp, rts/Rendering/GL/glExtra.cpp, rts/Sim/Units/CommandAI/MobileCAI.cpp, rts/Sim/Weapons/BeamLaser.cpp, rts/Sim/Weapons/LightningCannon.cpp, rts/Sim/Weapons/StarburstLauncher.cpp, rts/Sim/Weapons/Weapon.cpp, rts/Sim/Weapons/Weapon.h, rts/Sim/Weapons/WeaponDef.cpp, rts/Sim/Weapons/WeaponLoader.cpp
Some tags didn't need copying to the weapon class, since they are never changed, and don't rely on unit.
=> Weapon loader cleanup

rts/Map/MapInfo.cpp, rts/Map/MapInfo.h, rts/Map/SMF/SMFReadMap.cpp
added three more tags for the smf section of the mapinfo.lua file to override the type,metal and grass infomaps from greyscale images. if the file is missing or invalid dimensions a content_error exception will be thrown with an informative error message
=> added lua override for infomaps

rts/Lua/LuaUnitDefs.cpp, rts/Sim/MoveTypes/StrafeAirMoveType.cpp, rts/Sim/MoveTypes/StrafeAirMoveType.h, rts/Sim/Units/UnitDef.cpp, rts/Sim/Units/UnitDef.h
- add attackSafetyDistance unitDef (default 0 = current behavior)
- fighters abort dive toward target if within attackSafetyDistance and climb back to normal altitude
- this helps prevent collisions with ground and ground units
=> add attackSafetyDistance unitDef

doc/changelog.txt, rts/Lua/LuaConstCOB.cpp, rts/Rendering/ProjectileDrawer.cpp, rts/Sim/Projectiles/PieceProjectile.h, rts/Sim/Units/Scripts/UnitScript.cpp
if SFX.RECURSIVE is used in Explode(), the flying piece will be drawn together with its children.
(otherwise nothing is affected)
=> Add flag to draw exploded pieces recursively

rts/System/FileSystem/ArchiveScanner.cpp
Message will be like that: 
Error: Found a "/home/revenant/.spring/maps/deltasiegedry.sd7" already in "/home/revenant/.spring/maps/DeltaSiegeDry.sd7", ignoring second one
instead of (not very helpful in my case): 
Error: Found a "tempest.sd7" already in "/home/revenant/.spring/maps/", ignoring one in "/home/revenant/.spring/maps/"
=> fix #4784 Improve unitsync error messages n case of duplicated files

rts/Game/Players/PlayerHandler.cpp
This assert fires for no reason if you watch a demo through a script, since the local player is added before LoadFromSetup is called through the demo messages.
Since Spring.Reload() already works I think this can be safely deleted.
=> Remove assert from PlayerHandler.cpp

AI/Interfaces/Java/bin/jni_wrappCallback.awk, AI/Wrappers/CUtils/bin/common.awk, AI/Wrappers/Cpp/bin/wrappCallback.awk, AI/Wrappers/JavaOO/CMakeLists.txt, AI/Wrappers/JavaOO/bin/wrappCallback.awk, AI/Wrappers/LegacyCpp/AIAICallback.cpp, AI/Wrappers/LegacyCpp/AIAICallback.h, AI/Wrappers/LegacyCpp/IAICallback.h, rts/ExternalAI/Interface/AISCommands.h, rts/ExternalAI/Interface/aidefines.h, rts/ExternalAI/SSkirmishAICallbackImpl.cpp
[Lua<->AI communication](https://springrts.com/phpbb/viewtopic.php?f=15&t=26298) now works in 3/4-duplex (no ret_outData in SLuaMessageEvent).
Purpose of [ret_outData](https://github.com/spring/spring/blob/d1c9887f8e8c8931f5a71d73a82d05ac5c48e222/rts/ExternalAI/Interface/AISCommands.h#L412) from SCallLua(Rules|UI)Command was changed so now it points to a buffer where response should be copied, i.e. caller is responsible for providing proper buffer (or NULL).
I see 1 (dis)?advantage: buffer for ret_outData must have const size MAX_RESPONSE_SIZE=10240 chars (defined in aidefines.h). An alternative would be an additional "int outSizeMax" param in SCallLua(Rules|UI)Command. But that will require more hassle with heap memory opposed to stack in awk scripts, and such generated interface will …
=> Fix Lua.callRules, Lua.callUI for JavaOO

AI/Wrappers/Cpp/CMakeLists.txt, AI/Wrappers/Cpp/bin/wrappCallback.awk, AI/Wrappers/JavaOO/CMakeLists.txt, AI/Wrappers/JavaOO/bin/wrappCallback.awk, doc/changelog.txt, rts/ExternalAI/Interface/SSkirmishAICallback.h, rts/ExternalAI/SSkirmishAICallbackImpl.cpp, rts/ExternalAI/SSkirmishAICallbackImpl.h
This is basically a stub from [lua](https://github.com/spring/spring/blob/d7ebbb065cf8dcb6218ac2614a9830634623a8d7/rts/Lua/LuaSyncedRead.cpp#L3233), except that ally check done only once in skirmishAiCallback_Unit_getWeapon(s) while creating Weapon objects.
[Related discussion.](https://springrts.com/phpbb/viewtopic.php?f=15&t=33559)
Weapon usage example:
```C
Unit* u = ...;
auto wps = std::move(u->GetWeapons());
for (Weapon* wp : wps) {
if (wp->GetReloadFrame() <= currentFrame) printf("Ready to fire\n");
delete wp;
}
...
WeaponMount* wpMnt = ...;
Weapon* wp = u->GetWeapon(wpMnt);
if (wp->GetReloadFrame() <= currentFrame) printf("Ready to fire\n");
delete wp;
```
=> AI weapon state

rts/Sim/Weapons/LightningCannon.cpp
This fixes issues that LightningCannons have with hitting their target.The bug most obviously affects shieldfelon and armzeus from ZK.
The fix is similar to the fix for Rifle: https://github.com/spring/spring/commit/71b7fc3b7afb8132fdaf8da7b3b952110750562f
=> Fixed LightningCannon trouble with hiting targets.

doc/changelog.txt, rts/lib/lua/CMakeLists.txt, rts/lib/lua/include/LuaInclude.h
thoughts about this?
i'm unsure if this change is good or bad:
pro:
- allows to test for nans in lua code with release builds (debug is horrible slow)
- only rts/lib/lua has to be recompiled when enabled
con:
- when a nan is found it insta-desyncs which maybe leads to more confusion
- compile setting (runtime setting would be nicer, but slow)
- new compile setting = more complexity
(+things i can't think about atm)
maybe the better solution is to make the used lua a shared lib so functions can be replaced with the LD_PRELOAD trick?
=> add cmake option DEBUG_LUANAN to enable lua check for nans in a release build

rts/Sim/Projectiles/WeaponProjectiles/StarburstProjectile.cpp
The behaviour should not have been changed without reason. The change broke the timing and feel of a few weapons.
=> Readded acceleration in stage 3 of StarburstLauncher.

rts/Sim/MoveTypes/HoverAirMoveType.cpp, rts/Sim/MoveTypes/StrafeAirMoveType.cpp
Unit restTime is currently reset when the unit is shot, or when an air unit moves. Ground units can currently move without resetting restTime. This patch makes air units also able to move without resetting restTime, to keep consistency with ground units.
As a side note, FPSed planes don't reset restTime even if moving.
=> Remove restTime movetype interaction inconsistency

cont/base/maphelper/maphelper/mapdefaults.lua, cont/base/maphelper/maphelper/parse_tdf_map.lua, cont/base/springcontent/shaders/GLSL/SMFFragProg.glsl, rts/Map/MapInfo.cpp, rts/Map/MapInfo.h, rts/Map/SMF/SMFReadMap.cpp, rts/Map/SMF/SMFReadMap.h, rts/Map/SMF/SMFRenderState.cpp
Works similarly to the previous SSMF splatting, but instead of sampling a combined texture of 4 different single-channel diffuse detail textures, it samples four separate normal textures.
The textures must contain the normal maps in the RGB channel (standard normal maps), with a diffuse luminance in the alpha channel.
The system uses the same splatDistrTex as regular SSMF.
Usage:
Specify splatDetailNormalTex1 .. splatDetailNormalTex4 in the MAP resources section.
splatDetailTex will be unused if the above are present.
specify splatDetailNormalDiffuseAlpha=1 to enable diffuse textures stored in alpha channels
~10% performance cost of sampling 4 textures once each vs the previous 1 texture 4 times.
Screenshot: http://beherith.eat-peet.net/stuff/detail_normals.png
Example map: …
=> Add support for SSMF Detail Normal Textures

rts/ExternalAI/Interface/SSkirmishAICallback.h, rts/ExternalAI/SSkirmishAICallbackImpl.cpp, rts/ExternalAI/SSkirmishAICallbackImpl.h
Clone of [LuaSyncedRead::GetUnitShieldState](https://github.com/spring/spring/blob/323ab5a44293ee92ca70b12b6fdde0b0527ebe34/rts/Lua/LuaSyncedRead.cpp#L3127) as native AI don't have access to shield's state.
=> [AI] Shield state

rts/Sim/Units/Unit.cpp
The patch makes wrecks save the parent unit's speed from after UnitDestroyed (currently is before). This allows to set wrecks' initial speed reliably.
=> Allow SetUnitVelocity in UnitDestroyed

cont/LuaUI/widgets.lua
Add a field "default" to the list of known widgets, so that an individual widget can access a list of widgets that are enabled/disabled by default.
=> add field "enabled" to list of known widgets

rts/ExternalAI/Interface/SSkirmishAICallback.h, rts/ExternalAI/SSkirmishAICallbackImpl.cpp, rts/ExternalAI/SSkirmishAICallbackImpl.h, rts/Sim/Misc/ModInfo.cpp
According to [ModInfo.cpp](https://github.com/spring/spring/blob/6140fdde868985dbf05ba7d5126e17db5577664c/rts/Sim/Misc/ModInfo.cpp#L244) radarMipLevel is not constant (docstring says it's 8).
=> [AI] Add missing radarMiplevel and fix some docstrings

rts/Sim/MoveTypes/HoverAirMoveType.cpp, rts/Sim/Units/CommandAI/BuilderCAI.cpp
Aircons in Phoenix Annihilation (see https://github.com/CommanderSpice/Phoenix-Annihilation) have collision disabled.
They don't do proper circling without the modification in BuilderCAI.cpp. Instead they just clump together above the unit beeing build.
The other Modification randomizes the circling direction, so they kind of distribute.
The distribution looks like a circle when collision is disabled. With collision they use a spherical formation.
=> Circling construction plane fixes

rts/Sim/Weapons/Weapon.cpp
Was supposed to be 20 degrees but is 20 radians.
20 radians is 3*360 + 20 degrees (!) so logic doesn't change but this prevents failures if someone changes the value.
Relatedly, this whole check might be pointless because there's already the weaponDef->maxFireAngle check and that tag also defaults to 20 degrees.
=> Fix a constant - nlc

AI/Wrappers/Cpp/bin/wrappCallback.awk
Memleak caused by throw prior to delete[].
Before:
```
params = new float[params_raw_size];
for (int i=0; i < _size; ++i) {
params[i] = params_list[i];
}
internal_ret_int = bridged_Unit_executeCustomCommand(this->GetSkirmishAIId(), this->GetUnitId(), cmdId, params, params_size, options, timeOut);
if (internal_ret_int != 0) {
throw CallbackAIException("executeCustomCommand", internal_ret_int);
}
delete[] params;
```
After:
```
params = new float[params_raw_size];
for (int i=0; i < _size; ++i) {
params[i] = params_list[i];
}
internal_ret_int = bridged_Unit_executeCustomCommand(this->GetSkirmishAIId(), this->GetUnitId(), cmdId, params, params_size, options, timeOut);
if (internal_ret_int != 0) {
delete[] params;
throw CallbackAIException("executeCustomCommand", internal_ret_int);
}
delete[] …
```
=> [AI] Fix Cpp API memleak

rts/Net/NetCommands.cpp, rts/Sim/Units/UnitTypes/Factory.cpp
* if a factory changes team, move its buildee to that team as well
instead of removing it from queue
* allow to manually share nanoframes
=> Nanoframes:

rts/Sim/Units/Unit.cpp
The raw value is more useful and precise. Lim is always 0 - 1 so to catch changes at high raw values you'd need increasingly precise expGrade.
=> UnitExperience calls based on exp diff, not limExp

rts/System/LoadSave/CregLoadSaveHandler.cpp, rts/System/LoadSave/LuaLoadSaveHandler.cpp
ostream is an output, it doesn't seem logical to reset output in streamCopy (SkirmishAIWrapper.cpp)
Actually resetting istream after each AI started to use own load-stream is actually pointless with current usage. But still streamCopy, if it's really "copy", shouldn't change input in theory.
Edit: I should have probably mention earlier that this is not an enhancement, but a bug fix.
Currently each subsequent AI saves all previous data plus its own. Save/Load is broken.
=> [AI] Only istream gets reset, not ostream. Safe aiSize for CregLoadSave

rts/Sim/Units/UnitTypes/Factory.cpp, rts/Sim/Units/UnitTypes/Factory.h
This fixes units being built without a factory.
=> make sure there is no nanoframe left when a factory is destructed

rts/Rendering/GL/glStateDebug.cpp
Actually I don't know if DEBUG_GLSTATE=ON is deprecated, or even if you are planning to deprecate it. Anyway, I guess this tiny fix will not hurt
=> Fixing compilation errors when DEBUG_GLSTATE=ON

rts/Lua/LuaSyncedRead.cpp
Prevents allocating a bigass table when getting just one command. Getting just the front of the command queue is a fairly common action.
=> PackCommandQueue: dont overallocate array

rts/Sim/Units/Unit.cpp
To prevent the case where UnitFinished happens after UnitDestroyed.
=> Disallow building dead units

rts/Lua/LuaHandleSynced.cpp
Currently CallAsTeam does not temporarily cancel full read access. This means that, for example, GetUnitPosition returns the real position even if there's radar wobble (which means it's impossible to get the actual wobbled position because GetUnitPosErrorParams correctly returns nil, since the unit is enemy!)
=> CallAsTeam: full access only if AllAccessTeam

AI/Skirmish/AAI/data/cfg/mod/TA.cfg, rts/Sim/Units/CommandAI/BuilderCAI.cpp, rts/Sim/Units/CommandAI/CommandAI.cpp
Fix whitespace after newline in tooltips text for Fire state, Move state, Repeat and Trajectory.
Add newline to tooltips text for reclaim command.
=> Fix whitespaces and newlines in tooltips text

rts/Sim/Units/CommandAI/BuilderCAI.cpp
Before: a partially eaten wreck is considered fresh if it also has some resurrect progress.
After: a partially eaten wreck is never considered fresh.
=> Area rez: consider partially eaten wrecks nonfresh

cont/base/springcontent/LuaGadgets/gadgets.lua, doc/changelog.txt, rts/Game/SelectedUnitsHandler.cpp, rts/Lua/LuaHandle.cpp, rts/System/EventHandler.h
Previously:
* widgets run the callin "blind" (they dont know what the engine command would be)
* unsynced gadgets are run only if widgets dont return anything (they implicitly know widgets didnt override but dont know the engine command either)
Now:
* unsynced gadgets are run first, they receive the engine default cmd as 3rd param
* widgets are then run and receive current default (taking into account what gadgets said)
=> DefaultCommand call-in:

cont/base/springcontent/gamedata/defs.lua, cont/base/springcontent/gamedata/defs_post.lua, doc/changelog.txt, rts/Lua/LuaSyncedMoveCtrl.cpp, rts/Sim/MoveTypes/MoveDefHandler.cpp, rts/Sim/MoveTypes/MoveDefHandler.h, rts/Sim/Path/Default/PathConstants.h, rts/Sim/Path/Default/PathEstimator.cpp, rts/Sim/Path/QTPFS/PathManager.cpp, rts/Sim/Units/UnitDef.cpp
Currently movedefs keep refcounts based on unitdefs that use them. Any movedef that has 0 refs is then skipped when processing. This is bad:
* you can't use `Spring.MoveCtrl.SetMoveDef` for those movedefs.
* there's no point keeping such inaccessible movedefs in memory, wasteful.
Ergo:
* games should be able to explicitly specify which movedefs they are going to use.
* useless movedefs shouldn't even reach the engine.
This patch removes the refcounts; all movedefs provided by the game will be processed. It is now game's responsibility to say which movedefs it wants. For backward compatibility, the builtin defs parser now filters out unused movedefs.
=> Remove movedef refcounts

rts/Game/Game.cpp
LuaUI might want to access GRP on shutdown.
=> Kill LuaUI before clearing game rules params

rts/Lua/LuaUnsyncedRead.cpp, rts/Lua/LuaUnsyncedRead.h
Returns whether the built-in chat/label prompt is active
=> Add `Spring.IsUserWriting() -> bool`

doc/changelog.txt, rts/ExternalAI/Interface/SSkirmishAICallback.h, rts/ExternalAI/SSkirmishAICallbackImpl.cpp, rts/ExternalAI/SSkirmishAICallbackImpl.h
Ability to query captureProgress param should give AI more options to retreat/save its units.
Other params were added by Lua's GetUnitHealth analogy.
=> [AI] Reveal captureProgress, buildProgress and paralyzeDamage params.

rts/System/Net/UDPListener.cpp
http://www.boost.org/doc/libs/1_47_0/doc/html/boost_asio/reference/socket_base/non_blocking_io.html says it was deprecated since boost 1.47 (released 11.7.2011) and we are having trouble building this for @openSUSE Tumbleweed.
=> Avoid deprecated socket_base::non_blocking_io

buildbot/master/master.cfg
updated gcc version on the w64 buildbot to 5.5.0 from 4.9
=> updated gcc w64 buildbot

doc/changelog.txt, rts/Lua/LuaUnsyncedCtrl.cpp
MarkerAdd{Point,Line} now have an extra optional argument (after localOnly: 6th for point, 8th for line) the playerID of the player who should appear as the author of the drawing (if missing, defaults to the local player). Only has an effect when localOnly is true.
=>  Drawings callouts: allow to specify playerID

rts/Rendering/GL/LightHandler.h
Apparently SMF render was crashing because the number of vec4 uniforms was not correctly computed
=> Fix to 'invalid parameter array size' GLSL error

rts/Sim/Units/Unit.cpp
Reproduction: kill a unit using any form of damage with the following code on and observe how expected != actual.
```lua
local WEAPON_ID = -Game.envDamageTypes.Killed
local EXTRA_DMG = 100
function gadget:UnitDamaged(unitID, unitDefID, unitTeam, damage, paralyzer, weaponID)
if weaponID == WEAPON_ID then
return
end
local pre_HP = Spring.GetUnitHealth(unitID)
if pre_HP >= 0 then
return
end
Spring.Echo("health before: " .. pre_HP)
Spring.Echo("adding " .. EXTRA_DMG .. " damage")
Spring.AddUnitDamage(unitID, EXTRA_DMG, 0, -1, WEAPON_ID)
local post_HP = Spring.GetUnitHealth(unitID)
local expected_HP = pre_HP - EXTRA_DMG
Spring.Echo("health after: " .. post_HP .. ", expected " .. expected_HP) -- differs!
Spring.SetUnitHealth(unitID, expected_HP) -- negative HP is kosher
end
```
Negative HP is …
=> Fix GetUnitHealth under recursive AddUnitDamage

rts/Sim/Units/Unit.cpp
Replace a magic number (previously it made some sense because https://github.com/spring/spring/commit/be14d9c2ecbbd9fb9cacc56c02442164824e9071#diff-ed40a10d6489adbd290ee8870e244f93L272 was defined in terms of slowupdate but that is no longer the case)
=> add. be14d9c2ecbbd9fb9cacc56c02442164824e9071

rts/Map/HeightMapTexture.cpp
I don't think NEAREST has any particular reason to stay.
=> Changed the MAG_FILTER of $heightmap to LINEAR. 

buildbot/slave/osx/macos_sierra_x64.cmake, rts/Rendering/GL/myGL.h, rts/lib/headlessStubs/glewstub.h
why is include specified to be OPENGL if __APPLE__?
none of the distributions of glew (brew or macSDK) install it in that path
instead they use GL/glew.h
Thanks
=> not needed by macos buildbot [Question]

rts/Lua/LuaUI.cpp
This commit makes the lockluaui.txt file obsolete, and
Spring now acts as if this file always exists.
Most (all?) games are using this by default anyway:
```bash
find -L -iname  'lockluaui.txt'
./Zero-K.sdd/gamedata/LockLuaUI.txt
./SpringMCL.sdd/Gamedata/LockLuaUI.txt
./Balanced-Annihilation.sdd/gamedata/lockluaui.txt
./spring1944.sdd/gamedata/LockLuaUI.txt
./EvoRTS.sdd/Gamedata/lOCKlUAui.TXT
./JauriaRTS.sdd/Gamedata/lockluaui.txt
```
I don't think there is a use case for this anymore, although
I don't know why anyone would want to disable VFS for LuaUI anyway.
PS: I remember this wasting hours of my time when I was creating my
first Chili based mod, ages ago, so this is a way of enacting revenge.
=> Deprecate lockluaui.txt

rts/Lua/LuaIO.cpp, rts/Map/MapInfo.cpp, rts/Sim/Misc/DefinitionTag.h, rts/System/Platform/Win/WinVersion.cpp, rts/aGui/HorizontalLayout.cpp
1) Added includes for array and algorithm
2) Simultaneous definition of #include <windows.h> and #include <ntdef.h> cause huge number of redefinition errors somehow. Removed ntdef.h for now.
=> Changed a few things to make develop compile on MSVC

buildbot/slave/osx/macos_sierra_x64.cmake
this uses the system linker from apple instead of the gnu ones that fixes some build steps
=> attempt to fix some build steps on macos buildbot

rts/Game/UI/GuiHandler.cpp, rts/Game/UI/GuiHandler.h, rts/Game/UI/MiniMap.cpp, rts/Game/UI/MouseHandler.cpp, rts/Game/UI/MouseHandler.h
This PR adds the following springsettings:
- MouseDragSelectionThreshold
- MouseDragCircleCommandThreshold
- MouseDragBoxCommandThreshold
- MouseDragFrontCommandThreshold
Godde keeps commenting that he often right clicks on a unit with the intention to target it, but while doing so accidentally moves the mouse very slightly (because he is microing so hard). This movement leads the interface to interpret his input as an area command, which is likely to not include the desired unit. I have tried hacking some solutions for special cases, but it is a bit of a waste of time when the thresholds are so easily changed within the engine.
See http://zero-k.info/Forum/Post/197424#197424 and https://github.com/ZeroK-RTS/Zero-K/issues/3025
I also fixed an area command visualisation bug caused by …
=> Configurable drag selection and area command leeway v3

doc/changelog.txt, rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaSyncedRead.h
Spring.GetUnitCurrentCommand(unitID) -> [cmdID, cmdOpts (coded), cmdTag[, cmdParam1[, cmdParam2 ... ]]]
Options are coded as a single number and parameters are returned on the stack so that there are no table allocations. This is a form of optimisation because getting the current command is a common action but so far the only available option was GetUnitCommands(unitID, 1) which still allocated 3 tables.
=> Add `GetUnitCurrentCommand` lua callout

rts/Lua/LuaSyncedRead.cpp
LuaUI used to be unable to use the table-less version of GetUnitLosState (presumably because the value was not masked).
=> Expose tableless GetUnitLosState even if !FullRead

rts/Lua/LuaSyncedRead.cpp
other functions above (eg `IsEditDefsEnabled`) don't do a null check at all, probably either those should get one or the ones I touched here removed
=> fix some null checks

rts/Lua/LuaSyncedCtrl.cpp, rts/Lua/LuaSyncedCtrl.h
Features don't have a unit script so need a standalone callout. Units are mostly there for consistency since they already have `SetPieceVisibility` in LUS but being able to hide a unit's piece outside LUS (either because COB or for convenience) is also nice.
=> Add `Spring.Set{Unit,Feature}PieceVisible`

tools/DemoTool/DemoTool.cpp
The text players enter into map markers may be of interest.
Print all the other stuff too, because why not.
=> DemoTool: more verbose NETMSG_MAPDRAW

rts/Sim/MoveTypes/GroundMoveType.cpp
This PR changes the logic in CanSetNextWayPoint and splits allowSkip into allowSkip and facePoint.
Previously, CanSetNextWayPoint could return true if (allowSkip || rangeTest || facePoint). This caused waypoints to be skipped even if there was no free path to it's goal (!rangeTest) if it happened to be facing its goal (facePoint).
This change has CanSetNextWayPoint able to return true if (allowSkip || (rangeTest && facePoint)), which fixes the issue with the previous behaviour.
=> Waypoint skipping fix for Mantis 6206.

doc/changelog.txt, rts/Lua/LuaSyncedRead.cpp
Most existing games give visual feedback regarding both states so I think this is a preferable default behaviour.
=> `GetUnit{Armored,IsActive}`: allow enemies in los

rts/Lua/LuaSyncedRead.cpp
AllAccessTeam always succeeds the check at level "private" so there's no point checking it at level "allied".
=> micro-optimize Get*RulesParam

doc/changelog.txt, rts/Lua/LuaUnsyncedRead.cpp, rts/Lua/LuaUnsyncedRead.h
`Spring.GetCurrentCamera` returns the name of the current camera,
for example "ta" or "spring" (currently available under the `name`
key in the table returned by `Spring.GetCameraState`).
`Spring.GetCameraState` now accepts a boolean parameter; if it is
false then instead of allocating a table, it returns cam-specific
values onto the stack (use `GetCurrentCamera` first to know how to
interpret them; use `GetCamera{Position,Direction,FOV}` to get the
non-specific values from the base class). The returned values are:
fps, rot -> oldHeight
ta -> height, angle, flipped
spring -> rx, ry, rz, dist
free -> rx, ry, rz, vx, vy, vz, avx, avy, avz
ov -> (nil)
=> Add `GetCurrentCamera`, tableless `GetCameraState`

rts/Sim/MoveTypes/GroundMoveType.cpp
My previous PR (https://github.com/spring/spring/pull/455) made it too difficult to skip waypoints, which caused units to circle on the spot when given new move commands. This PR removes the facePoint check for waypoint skipping. I have not found any issues with removing the facePoint test. It will require live testing and feedback.
Before my previous PR a waypoint could be skipped if (allowSkip || rangeTest || facePoint). The behaviour proposed here is (allowSkip || rangeTest). I tested and there is no regression for the waypoint skipping PR. The skipping check in this PR is harder to satisfy than prior to either PR, so it is unlikely that there is a regression in other behaviour. I did some testing of units that initially can skip waypoints but which become blocked due to their turning …
=> Fix circling at the start of paths

doc/changelog.txt, rts/Lua/LuaSyncedCtrl.cpp, rts/Lua/LuaSyncedCtrl.h
Finishes current command.
* similar to `CMD.REMOVE`, but puts the command back onto the queue with the Repeat state.
* similar to returning `true, true` from `CommandFallback` but works on builtin engine commands.
=> Add `Spring.UnitFinishCommand(unitID)`

cont/base/springcontent/shaders/GLSL/ShadowGenVertProg.glsl
> error: type mismatch for varying parameter (named {shadowViewMat, shadowProjMat, vertexModelPos}) between shader stages
=> Probably fixed https://github.com/ZeroK-RTS/CrashReports/issues/23539

rts/System/SpringApp.cpp
`game` can be a null pointer when LuaMenu calls `SpringApp::Reload`.
In practice this didn't cause many problems, as this gets optimised as
a fixed function call, with a null `this` parameter. This led it to be
left unnoticed.
However, when using tools that are stricter about bad behaviour
(-fsanitize=...), this would detect a null pointer dereference and
abort the program.
Encountered incidentally during mantis #6327.
=> Prevent nullpo in LuaMenu Reload call

rts/Sim/Weapons/Rifle.cpp
I don't think anybody is using Rifles (harcoded low-quality particles being one of the reasons!) so this should do no harm and is fairly easy to replicate with Lua. On the other hand, Rifle could become more useful as a very simple hitscan weapon (simpler than BeamLaser which still involves a projectile).
=> Rifle weapontype: remove hardcoded particles

rts/ExternalAI/SSkirmishAICallbackImpl.cpp
LegacyCpp AI interface wrapper is written in a way that expects real array size as return value after [1st call](https://github.com/spring/spring/blob/39f8fbd47f112f067999366d0444fa591480f9b3/AI/Wrappers/LegacyCpp/AIAICallback.cpp#L295) with outArray=nullptr. The issue could be fixed on LegacyCpp level (pass INT_MAX instead of 0), but then in general C interface becomes inconsistent with similar functions like [getLosMap](https://github.com/spring/spring/blob/39f8fbd47f112f067999366d0444fa591480f9b3/rts/ExternalAI/SSkirmishAICallbackImpl.cpp#L1946-L1957).
(Fixes KAIK, please populate to maintenance)
=> [AI] Fix Command_getParams

rts/Sim/Misc/ModInfo.cpp, rts/Sim/Misc/ModInfo.h, rts/Sim/Units/Unit.cpp
This controls whether sight distance is used as a filter on proximity cloak checks, allowing for cheap implementations of the behaviour desired by FLOZi for s44 and myself for ZK.
Added a missing comment for alwaysVisibleOverridesCloaked.
See:
* https://springrts.com/mantis/view.php?id=6306 - Behaviour change requested by FLOZi.
* https://github.com/spring/spring/commit/ca1557cdee3fe4075ff9d987dfe0926a229146d6 - Behaviour change implemented.
* https://springrts.com/mantis/view.php?id=6374 - My ticket when I noticed that the behaviour changed.
* http://zero-k.info/Forum/Thread/29941 - Thread reporting the change.
=> Added the modrule decloakRequiresLineOfSight

rts/Sim/Misc/ModInfo.cpp, rts/Sim/Misc/ModInfo.h, rts/Sim/Units/Unit.cpp
I don't know if separate PRs are desired, but I made the changes to test them so here it is. See https://github.com/spring/spring/pull/498
=> decloakRequiresLineOfSight for maintenance

rts/Sim/MoveTypes/GroundMoveType.cpp
collideeMD can be a nullptr, as it is stated in https://github.com/spring/spring/blob/develop/rts/Sim/MoveTypes/GroundMoveType.cpp#L2008:
const bool collideeMobile = (collideeMD != nullptr); // maybe true
And indeed it happens with every single unit which does not needs SAT, right after building it in a factory. Thus, calling to collideeMD->CalcFootPrintAxisStretchFactor() is making the engine crash.
=> Fixed invalid collideeMD usage when modInfo.allowSepAxisCollisionTest = true

rts/Sim/MoveTypes/GroundMoveType.cpp
collideeMD can be a nullptr, as it is stated in https://github.com/spring/spring/blob/develop/rts/Sim/MoveTypes/GroundMoveType.cpp#L2008:
const bool collideeMobile = (collideeMD != nullptr); // maybe true
And indeed it happens with every single unit which does not needs SAT, right after building it in a factory. Thus, calling to collideeMD->CalcFootPrintAxisStretchFactor() is making the engine crash.
=> Fixed invalid collideeMD usage when modInfo.allowSepAxisCollisionTest = true (maintenance)

rts/Map/SMF/ROAM/RoamMeshDrawer.cpp
Patch::ComputeVariance only needs to be called if patch is visible and dirty. Before this change it was called even if tesselMesh was true, as the return value of |= is equal to tesselMesh. 
Thus if tesselMesh was set to true previously by a visibility change, then all subsequence patches would get their variance recomputed (which is quite expensive)
=> Port ROAM computevariance fix to maintainance.

rts/Lua/LuaSyncedCtrl.cpp
Unlike most lua_is* functions, lua_isnumber checks to see if the
given value *can* be a number, rather than if it currently is one:
> Returns 1 if the value at the given acceptable index is a number or
> a string convertible to a number, and 0 otherwise.
This means that even if a lua caller expressly coerces to string
beforehand, as long as the string looks like a number, it gets stored
as a number. This can cause problems if, for example, a player name
that looks like a very large number loses precision.
See esainane/zkstats@99ddb35 for an example.
Explicitly checking using the lua_israwnumber variant allows the caller
to provide either a string or a number, and have it be stored as such.
`develop` variant of #503.
=> Coerce to number less often in *SetRulesParam

rts/Map/Ground.cpp, rts/Map/SMF/ROAM/Patch.cpp, rts/Map/SMF/ROAM/Patch.h, rts/Map/SMF/ROAM/RoamMeshDrawer.cpp, rts/Map/SMF/ROAM/RoamMeshDrawer.h
ROAM frees up the entire triangle pool that stores the triangles of each tesselated patch (129*129 hmap pixels) and retesselates all patches whenever any in the visibility of patches occures, or if the unsynced heightmap changes (e.g.) explosion
LOAM does nothing when patches only go out of view, or when patches go into view, and a not-too-stale tesselation is aviable
when a 'stale' patch comes into view, only it is retesselated, and retesselation can affect neighbours, which is tracked and updated accordingly
when a heightmap change occurs, only that patch is retesselated, and if the neighbours are affected, that is updated accordingly
The cost: the mildly increased memory cost of keeping a larger triangle pool updated
the advantage is lag-free scrolling on a map
If the LOAM triangle …
=> LOAM (Lazy ROAM) for develop branch

rts/Sim/Units/UnitTypes/Builder.cpp
See https://github.com/spring/spring/pull/516
`!teamHandler.Ally(allyteam, cu->allyteam)` is incorrect because allied allyteams do not necessarily share LOS. This loop only needs to detect units 'u' that people would like to assist when they find it blocking their own construction.
=> Fix non-visible enemy units and structures not blocking construction, now small enough to have a chance of being pulled.

doc/changelog.txt, rts/Lua/LuaHandle.h, rts/Lua/LuaUnsyncedCtrl.cpp
Games which don't want those functions used can just do `Spring.SetUnitNoFoo = nil` at LuaUI entry point.
=> Spring.SetUnitNoFoo: expose to LuaUI

rts/Net/GameServer.cpp
According to @abma this setting should ideally be disabled for autohosts, https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/789#issuecomment-139229098
=> AllowSpectatorJoin defaults to 0 for dedi

rts/Lua/LuaVFS.cpp
This is the best way (or the most robust at least) I found to fix the problem.
With these changes my widget may works either using...
* the archive name (e.g. 1944_Moro_River_V1)
* the file name (e.g. 1944_moro_river_v1.sd7)
* the local filepath (e.g. maps/1944_moro_river_v1.sd7)
* ~~the absolute filepath (e.g. /home/user/.spring/maps/1944_moro_river_v1.sd7)~~ (This was actually a widget trick)
**Tested just on maintenance version**
=> Fix to #6376 (development version)

rts/Lua/LuaUnitDefs.cpp, rts/Sim/Units/CommandAI/MobileCAI.cpp, rts/Sim/Units/UnitDef.cpp, rts/Sim/Units/UnitDef.h
The PR adds a tag to disable MobileCAI giving move orders while attacking. It is a step towards making polishing starcraft-style unit interactions.
Without this change units set to maneuver or roam move along with their target, even when in range.I do not want to use hold position because it removes idle target acquisition and affects fight.
This is a compatible changed cherry picked from the fork I referenced in this ticket: https://springrts.com/mantis/view.php?id=6199
=> Added stopToAttack 

rts/Rendering/GL/RenderDataBuffer.hpp
/home/travis/build/spring/spring/rts/Rendering/GL/RenderDataBuffer.hpp:169:12: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
=> Fix pessimizing std::move / allow copy elision

rts/Rendering/Env/Decals/LegacyTrackHandler.cpp
This allows defining units which both leave tracks on ground and float on water, such as bots that swim on the surface.
=> Fix floating units leaving tracks on sea floor

rts/Game/UI/MiniMap.cpp
This changes render behaviour of CMiniMap::RenderCachedTexture to match
CMiniMap::DrawForReal.
=> MiniMap: Fix useNormalizedCoords DualScreenMode

rts/System/Sync/SHA512.cpp
=> Add missing include

rts/build/cmake/FindAsciiDoc.cmake
In my manjaro docbook-xsl version is 1.79.2, which is not considered [in the prefixed list](https://github.com/spring/spring/blob/develop/rts/build/cmake/FindAsciiDoc.cmake#L38), so it fallbacks to [file based search](https://github.com/spring/spring/blob/develop/rts/build/cmake/FindAsciiDoc.cmake#L51).
Unfortunately, if I manually type the list command I get 2 files:
```
$ ls /usr/share/xml/docbook/xsl-stylesheets-*/manpages/docbook.xsl
/usr/share/xml/docbook/xsl-stylesheets-1.79.2/manpages/docbook.xsl  /usr/share/xml/docbook/xsl-stylesheets-1.79.2-nons/manpages/docbook.xsl
```
Driving to errors. This PR fix that error, getting just the first found file. Tested just on maintenance version in my current computer.
=> Fix building errors for non-prefixed docbook versions

rts/builds/dedicated/CMakeLists.txt
This allows Windows users to actually see the output of spring-dedicated.exe without having to redirect it.
This is already done correctly for spring-headless, but for some reason it seems it was forgotten for spring-dedicated.
=> Set SUBSYSTEM CONSOLE for Windows system

doc/changelog.txt, rts/Sim/Features/FeatureDefHandler.cpp, rts/Sim/Units/UnitDef.cpp
More natural and it's also the key under which the value later gets exposed to wupgets.
`maxDamage` (or `damage` for features) still accepted because it's the TA spelling and what is currently used.
=> Unit/Feature defs loading: accept `health`

rts/System/GlobalRNG.h
Provide result_type member type in PCG32, which makes it compatible with C++ UniformRandomBitGenerator and, as result, makes it usable in std::shuffle (which deprecated std::random_shuffle calls in Spring should be replaced with).
=> Provide PCG32::result_type
