rts/Game/GameVersion.cpp, rts/Game/GameVersion.h, rts/Sim/Misc/ModInfo.cpp, rts/Sim/Misc/ModInfo.h, rts/Sim/Units/Unit.cpp, rts/lib/lua/include/LuaUser.cpp
(also added the new experience fix by kloot)
=> Unitsync crash fix

rts/Rendering/Env/AdvSky.cpp
Don't merge yet, I haven't tested ingame :)
=> More infotexture whitening fix

rts/Map/MapInfo.cpp, rts/Rendering/TeamHighlight.cpp, rts/Sim/Misc/GlobalConstants.h, rts/Sim/Misc/NanoPieceCache.cpp, rts/Sim/Misc/TeamStatistics.h, rts/Sim/MoveTypes/GroundMoveType.cpp, rts/Sim/Units/Unit.h, rts/Sim/Units/UnitHandler.cpp
This PR is to fix incorrect self-d timers as well as the incorrect tooltip and unitdefs interpretations across the entire economy. I would like technical feedback because I have had no negative feedback yet but it is likely that it exists.
Forum thread: https://springrts.com/phpbb/viewtopic.php?f=12&t=33041
=> Slow update change

rts/Map/SMF/SMFMapFile.cpp, rts/Map/SMF/SMFMapFile.h, rts/Map/SMF/SMFReadMap.cpp
this fixes the unitialised memory being used as a grass map.
=> fixed unitialised memory being used as grassmap

rts/Lua/LuaWeaponDefs.cpp
* dynDamageExp
* dynDamageMin
* dynDamageRange
* dynDamageInverted
* flightTime
=> Expose some weapon def tags to Lua nuggets

rts/ExternalAI/Interface/SSkirmishAICallback.h, rts/ExternalAI/SSkirmishAICallbackImpl.cpp, rts/ExternalAI/SSkirmishAICallbackImpl.h
Feature related discussions:
http://zero-k.info/Forum/Thread/12984
https://springrts.com/phpbb/viewtopic.php?f=15&p=568517#p568517
Brief issue description: native AI lacks economy information.
P.S. Can someone please explain to me how it works. Do i need to create a mantis ticket every time a feature/fix is added? Or just wait before it's been noticed?
=> [AI] Reveal Pull, Share, Sent, Received and Excess Economy's params

cont/LuaUI/widgets.lua, cont/base/springcontent/LuaGadgets/callins.lua, cont/base/springcontent/LuaGadgets/gadgets.lua, doc/changelog.txt, rts/Lua/LuaHandle.cpp, rts/Lua/LuaHandle.h, rts/Sim/Units/Unit.cpp, rts/System/EventClient.h, rts/System/EventHandler.h, rts/System/Events.def
UnitStunned(unitID, unitDefID, unitTeam, stunned)
Called whenever a unit's stun status changes (ie. gets stunned, or stun wears off)
=> Add UnitStunned call-in

rts/Lua/LuaSyncedCtrl.cpp, rts/Lua/LuaSyncedCtrl.h, rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaSyncedRead.h
Hopefully this passes muster. If not, please give feedback.
(Hoko fixed the git mess. <3)
=> Resolve Mantis #3900 with Spring.{Get,Set}UnitMaxRange

rts/Map/BaseGroundDrawer.cpp
The current default is quite bad because the settings were invalidated by the new infotex system. The previous settings looked like the ZK settings from before ZK updated its values. The new settings are the new ZK default.
=> Los recolor for some decent defaults.

rts/Game/Camera/FreeController.cpp
Paraphrased from old wiki page
=> Descriptions for CamFree{Gravity, AutoTilt, GroundOffset}

rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaSyncedRead.h
Spring.GetUnitFeatureSeparation(unitID, featureID[, dist2D])
Spring.GetFeatureSeparation(featureID1, featureID2[, dist2D])
There is Spring.GetUnitSeparation(unitID1, unitID2[, dist2D]), this is the extension to features, and unit vs feature distances.
=> Add LUA Synced read functions:

rts/ExternalAI/SSkirmishAICallbackImpl.cpp
[#4962](https://springrts.com/mantis/view.php?id=4962)
=> [AI] Fix cheats (#4962)

rts/Net/NetCommands.cpp
The decision to block this belongs to the mod.
=> Manual unit share: allow EMPed units

doc/changelog.txt, rts/Lua/LuaVFS.cpp, rts/Lua/LuaVFS.h, rts/builds/headless/CMakeLists.txt, rts/builds/legacy/CMakeLists.txt
interested if there are any objections before merging this.
see https://github.com/spring/spring/pull/221#commitcomment-13841525 and comments below
=> add VFS.CalcMd5 function

rts/Lua/LuaSyncedRead.cpp
Was already implemented, just not available
=> Expose Spring.GetFeatureVelocity

rts/ExternalAI/Interface/SSkirmishAICallback.h, rts/ExternalAI/SSkirmishAICallbackImpl.cpp, rts/ExternalAI/SSkirmishAICallbackImpl.h
=> AI sensors

rts/Rendering/Map/InfoTexture/Modern/Combiner.cpp
https://springrts.com/mantis/view.php?id=4995
=> Fix metal->los info texture switching visual harshness mantis #4995

AI/Wrappers/Cpp/CMakeLists.txt
=> add float3.cpp to AI/Wrappers/Cpp lib

doc/changelog.txt, rts/Game/UnsyncedGameCommands.cpp, rts/Map/BaseGroundDrawer.h, rts/Map/SM3/SM3GroundDrawer.cpp, rts/Map/SM3/SM3GroundDrawer.h, rts/Map/SMF/SMFGroundDrawer.cpp, rts/Map/SMF/SMFGroundDrawer.h
to change ground detail on the fly
=> add '/GroundDetail <value>'

buildbot/slave/rsync.sh
=> Increase upload bandwith

rts/Game/SyncedGameCommands.cpp, rts/Game/UnsyncedGameCommands.cpp, rts/Sim/Misc/ModInfo.cpp, rts/Sim/Misc/ModInfo.h
https://springrts.com/mantis/view.php?id=5259
related:
https://springrts.com/mantis/view.php?id=5257
=> Add allowTake modrule (fix #5259)

rts/Sim/Units/Unit.cpp
Else you can reclaim a storage while keeping its benefits.
=> Reverse nanoframing removes storage

cont/base/maphelper/maphelper/mapdefaults.lua
See https://github.com/spring/spring/blob/develop/rts/Map/MapInfo.cpp#L168
=> Fix wrong maphelper default splat values

AI/Interfaces/Java/data/jvm.properties, AI/Interfaces/Java/src/main/native/JavaBridge.c
=> Update JVM Memory limits to current decade

rts/Net/NetCommands.cpp
Allows receiver-AI to better operate with its income (based on resources going from sender-AIs).
Makes NETMSG_AISHARE seem more like NETMSG_SHARE.
=> Update sent and received values on NETMSG_AISHARE

rts/Sim/Misc/DamageArrayHandler.cpp
Halley's Comment - next appearance on Spring 140!
=> Remove old warning that no longer appears

cont/base/springcontent/LuaGadgets/gadgets.lua, doc/changelog.txt, rts/Lua/LuaHandleSynced.cpp, rts/Lua/LuaHandleSynced.h, rts/Net/NetCommands.cpp, rts/System/EventClient.cpp, rts/System/EventClient.h, rts/System/EventHandler.cpp, rts/System/EventHandler.h
Useful for AIs who always report playerID 255 (also convenience)
=> AllowStartPosition now receives 9th parameter teamID

rts/Lua/LuaConstGame.cpp
=> Lua: add a table with environmental damage def IDs

rts/Sim/Misc/ResourceHandler.cpp, rts/Sim/Misc/ResourceHandler.h
[One of the mem-leaks reported by AddressSanitizer](https://github.com/spring/spring/blob/57759758537a8110b5b8f0c1e2500ab0308ba985/rts/Sim/Misc/ResourceHandler.cpp#L137)
=> [AI] Fix direct mem leak @ResourceHandler.cpp:137

rts/ExternalAI/SSkirmishAICallbackImpl.cpp
Return proper floatOnWater.
~~RAI's (legacy API) naval ability will remain broken.~~
Damn those AI API layers. RAI also fixed.
=> [AI] Fix UnitDef::IsFloater()

.gitignore, rts/Game/Players/PlayerHandler.cpp, rts/Rendering/GL/Light.h, rts/Sim/MoveTypes/MoveType.h
Added a few missing headers and updated gitignore.
=> Trivial fixes for Visual Studio

rts/Sim/Projectiles/ExplosionGenerator.cpp
Same as the above-ground lenience. Closes #301
=> Expand CEG underground lenience (1 → 20 elmo)

doc/changelog.txt, rts/Game/Camera/OverheadController.cpp, rts/Game/Camera/OverheadController.h
* max height now configurable (closes #279)
* changeable on the fly
=> Overhead camera config:

rts/Lua/LuaSyncedCtrl.cpp
If the builderID parameter is passed to Spring.CreateUnit, the builder is considered the unassistable one if canBeAssisted=false.
=> Fix Spring.CreateUnit with canBeAssisted=false

rts/ExternalAI/SkirmishAIWrapper.cpp
Only 1 AI gets AIData. Others don't because loadStream is invalid.
=> Fix streamCopy

rts/ExternalAI/EngineOutHandler.cpp, rts/ExternalAI/EngineOutHandler.h, rts/System/LoadSave/CregLoadSaveHandler.cpp, rts/System/LoadSave/LuaLoadSaveHandler.cpp
An attempt to separate ai saving into separate streams/files.
I suck at streams, and logic seems to depend on order of skirmishAIIds more than on actual saved data.
But it worked :)
Tested lua-saving - works for me.
Not sure how to test creg-saving.
=> [AI] Save/Load AI data in separate streams

rts/Lua/LuaSyncedCtrl.cpp
Previously: 2nd arg means unit def name if string, rez progress if number
Now: 2nd arg means unit def name if string, unit def id if number. Rez progress is 4th arg
=> SetFeatureResurrect:

doc/changelog.txt, rts/Sim/Units/Scripts/UnitScript.cpp, rts/Sim/Units/UnitDef.cpp
=> Allow firestate 3 in cob and unitdef

rts/ExternalAI/AICallback.cpp
Currently IsNeautral can be read only if unit is in los. I'm unsure about the original purpose of neutral flag;  this change allows to read its value in IN_LOS or IN_RADAR (sonar is IN_RADAR, right?)
related: https://github.com/rlcevg/CircuitAI/issues/59
=> [AI] Make IsNeutral available in los or radar

buildbot/master/master.cfg, buildbot/slave/osx/macos_sierra_x64.cmake, rts/System/Platform/Misc.cpp
this modifies the master.cfg file of the buildbot and adds a cmake file with the cmake options
=> Add macos buildslave

rts/Sim/Units/Scripts/UnitScript.cpp
Previously it was the same as regular wake
=> `SFX.REVERSE_WAKE` now actually reverse

rts/Game/GameHelper.cpp, rts/Sim/Misc/GlobalConstants.h
Type changed to int because it's really a number of frames.
=> Replace a magic constant

cont/base/springcontent/shaders/GLSL/GuiFragProg4.glsl, rts/Rendering/Fonts/CFontTexture.cpp, rts/Rendering/Fonts/glFont.cpp, rts/aGui/Button.cpp, rts/aGui/Gui.cpp, rts/aGui/GuiElement.cpp, rts/aGui/GuiElement.h, rts/aGui/HorizontalLayout.cpp, rts/aGui/LineEdit.cpp, rts/aGui/List.cpp, rts/aGui/Picture.cpp, rts/aGui/VerticalLayout.cpp, rts/aGui/Window.cpp
Here I put some GL4 changes. Note that I made some changes before forking so I may have lost some files (but most likely and hopefully not). I tried to test my changes with the very latest state of the repo, but unfortunately I seem to be getting SIGFPE signals with sound? The PR worked with the earlier version (12 hours ago) of the repo well:
https://springrts.com/phpbb/viewtopic.php?f=11&t=36843
I hope this is useful. I tried to get the main menu display working as it seems the general strategy as described in the forums seems to be get stuff working -> see what's removed in the core profile and work on that next? I hope this is up to code standards, and apologies if not.
=> GL4 changes in UI and font rendering

rts/Lua/LuaUtils.cpp
To reduce array spam for the case where the table only contains 1 entry:
`Spring.GiveOrder(unit, {foo}, opt)` -> `Spring.GiveOrder(unit, foo, opt)`
I also considered allowing `nil` for param-less commands (like STOP or WAIT) that currently take `{}` and decided that could be confusing and error-prone. Some way to skip the array would be good here too though, possibly the current patch is good enough since you can pass a fake number there.
=> GiveOrder*: allow number as param

rts/Rendering/GlobalRendering.cpp
allows to start spring with mesa drivers / opengl 4.5 (core profile)
without these changes spring can't be started...
=> make some opengl extensions optional:

rts/Rendering/Textures/Bitmap.cpp
Those constexpr are not valid to my GCC-8.1.1 compiler
=> Fixed invalid constexpr

.travis.yml
=> Add CMake linter to travis

rts/ExternalAI/Interface/AISCommands.h
1) Update submodule
2) Remove SetWantedMaxSpeed() from NewOO_AI_API
I guess those changes should go into maintenance too
=> SetWantedMaxSpeed leftovers

rts/Lua/LuaMemPool.cpp, rts/Rendering/IconHandler.cpp, rts/Rendering/IconHandler.h, rts/Rendering/Textures/ColorMap.cpp
=> Unbitrot MSVC build on develop

rts/Sim/Weapons/BombDropper.cpp
Cannon was fixed but the cannon variante of aircraft bomb was not.
=> addendum a11cc90291ccb440e2f1d9a44cb631a332e6c0e2

cont/LuaUI/callins.lua, cont/LuaUI/widgets.lua
Please port over to maintenance too
=> Exposed(?) Draw{Units,Features}PostDeferred to LuaUI

rts/lib/lua/src/lmathlib.cpp
Convenience for the commonly used value.
=> Add `math.tau`

rts/ExternalAI/SSkirmishAICallbackImpl.cpp
Inability to read enemy's current shield power drives me crazy.
=> [AI] Read enemy weapons in los

rts/Sim/Misc/TeamBase.h
it seems no one tried to use player handicap in nearly 10 years
(discussion [here](https://github.com/spring/spring/commit/95b295b0ca07c6c08463a04a0d1d800ebbdf3e21#r37501043))
=> fix SetAdvantage function to allow negative values

rts/Map/SMF/ROAM/Patch.cpp
Causeing reupload of all VBO's every frame, as these functions dont exist in develop
=> LOAM: cherry pick from develop missed the updates in these two functions

doc/changelog.txt, rts/Sim/Weapons/Cannon.h, rts/Sim/Weapons/StarburstLauncher.cpp
Resolves mantis #6382: https://springrts.com/mantis/view.php?id=6382
=> Cannon: Use autoTargetRangeBoost when set

cont/LuaUI/widgets.lua
`widgetHandler:GameProgress` already exists.
=> Add GameProgress to builtin LuaUI

rts/Sim/Projectiles/WeaponProjectiles/BeamLaserProjectile.cpp
=> Beamlasers: 0 thickness disables rendering

buildbot/master/master.cfg
setting this in  github settings 
Payload url:
http://buildbot.springrts.com/change_hook/github?project=spring/spring
Content type:
x-www-form-urlencoded
and create a secret phrase
=> add github webhook

rts/Sim/Units/UnitHandler.cpp
Nanotowers can build mobiles all right.
=> Fix an obsolete comment
